const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const K={e:"sk2_e",d:"sk2_d",c:"sk2_c",a:"sk2_a",cr:"sk2_cr"};
const AUTH_KEY="sk2_auth",SESSION_KEY="simkoja2";
const defaultAuth={admin:{name:"Fendi",username:"fendi",password:"5432"},user:{name:"User",username:"user",password:"1234",employeeId:"EMP-001"}};
let currentRole=sessionStorage.getItem("simkoja_role")||(sessionStorage.getItem("simkoja2")==="1"?"admin":"");
let currentUsername=sessionStorage.getItem("simkoja_username")||"";
const authConfig=()=>{let auth={...defaultAuth,...get(AUTH_KEY,{})};auth.users=Array.isArray(auth.users)?auth.users:(auth.user?[auth.user]:[]);auth.user=auth.users.find(u=>u.username===currentUsername)||auth.user||auth.users[0]||defaultAuth.user;return auth};
const saveAuth=auth=>{auth.users=auth.users||[auth.user];auth.user=auth.users.find(u=>u.username===currentUsername)||auth.users[0]||defaultAuth.user;put(AUTH_KEY,auth)};
const isAdmin=()=>currentRole==="admin";
const owned=id=>isAdmin()||id===authConfig().user.employeeId;
const TYPES=["KTP","CV","Ijazah","Transkrip Nilai","STR","SIP","SIPP","SK Pengangkatan","SK Jabatan","Sertifikat Kompetensi","Sertifikat Pelatihan","Sertifikat BLS","Sertifikat BTCLS","Sertifikat PPI","Sertifikat Kamar Operasi","Sertifikat Anestesi","Kredensial","Kewenangan Klinis","Surat Penugasan","Dokumen Kepegawaian","Dokumen Lainnya"];
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const get=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},put=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const empName=id=>E.find(x=>x.id===id)?.name||"-";
const fmt=d=>d?new Date(d).toLocaleDateString("id-ID",{day:"2-digit",month:"short",year:"numeric"}):"-";
const day=d=>{if(!d)return null;let a=new Date();a.setHours(0,0,0,0);let b=new Date(d);b.setHours(0,0,0,0);return Math.ceil((b-a)/864e5)};
const st=d=>{if(!d)return["TIDAK BERBATAS","sb"];let n=day(d);return n<0?["EXPIRED","sr"]:n<=30?["SEGERA EXPIRED","so"]:n<=60?["AKAN EXPIRED","sy"]:["AKTIF","sg"]};
const bytes=n=>{if(!n)return"0 B";let u=["B","KB","MB","GB"],i=0;while(n>1024&&i<3){n/=1024;i++}return n.toFixed(i?1:0)+" "+u[i]};
const ini=n=>String(n||"").split(" ").filter(Boolean).slice(0,2).map(x=>x[0]).join("").toUpperCase();
let E,D,C,A,CR,fileSel=null;

function seed(){
 if(!localStorage.getItem(K.e))put(K.e,[
 {id:"EMP-001",name:"Ns. Palupi Mardika, S.Kep",nip:"198701012016012001",profession:"Perawat",position:"Perawat Muda",unit:"Kamar Operasi",status:"AKTIF",phone:"081234567890",email:"palupi@example.local",license:"SIPP-001"},
 {id:"EMP-002",name:"Ns. Nurhayati, S.Kep",nip:"198802022017012002",profession:"Perawat",position:"Perawat Muda",unit:"Kamar Operasi",status:"AKTIF",phone:"081234567891",email:"nurhayati@example.local",license:"SIPP-002"},
 {id:"EMP-003",name:"Ns. Riani Primaningsih, S.Kep",nip:"198903032018012003",profession:"Perawat",position:"Perawat Pelaksana",unit:"Kamar Operasi",status:"AKTIF",phone:"081234567892",email:"riani@example.local",license:"SIPP-003"},
 {id:"EMP-004",name:"Sri Muhyani, AMK",nip:"199004042019012004",profession:"Perawat",position:"Perawat Pelaksana",unit:"Kamar Operasi",status:"AKTIF",phone:"081234567893",email:"sri@example.local",license:"SIPP-004"},
 {id:"EMP-005",name:"Nia Apriliyanti, AMK",nip:"199105052020012005",profession:"Perawat",position:"Perawat Pelaksana",unit:"Kamar Operasi",status:"AKTIF",phone:"081234567894",email:"nia@example.local",license:"SIPP-005"},
 {id:"EMP-006",name:"Ricky Fauzi, AMK",nip:"199206062021012006",profession:"Perawat",position:"Perawat Pelaksana",unit:"Kamar Operasi",status:"AKTIF",phone:"081234567895",email:"ricky@example.local",license:"SIPP-006"},
 {id:"EMP-007",name:"dr. Eva, Sp.An",nip:"197707072010012007",profession:"Dokter",position:"Dokter Anestesi",unit:"Anestesi",status:"AKTIF",phone:"081234567896",email:"eva@example.local",license:"SIP-AN-007"},
 {id:"EMP-008",name:"dr. Raden Hari, Sp.An",nip:"197808082010012008",profession:"Dokter",position:"Dokter Anestesi",unit:"Anestesi",status:"AKTIF",phone:"081234567897",email:"radenhari@example.local",license:"SIP-AN-008"},
 {id:"EMP-009",name:"Fendi Warsito, A.Md.Kep",nip:"199309092022012009",profession:"Penata Anestesi",position:"Penata Anestesi",unit:"Anestesi",status:"AKTIF",phone:"081234567898",email:"fendi@example.local",license:"SIP-PA-009"},
 {id:"EMP-010",name:"Ns. Bela Novi Anggara, S.Kep",nip:"199410102023012010",profession:"Perawat",position:"Perawat Pelaksana",unit:"Recovery Room",status:"AKTIF",phone:"081234567899",email:"bela@example.local",license:"SIPP-010"}]);
 if(!localStorage.getItem(K.d)){const img="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=";put(K.d,[
 {id:"DOC-1",employeeId:"EMP-001",type:"STR",number:"STR-001/2026",issue:"2026-01-10",expiry:"2028-01-10",fileName:"STR_Palupi.pdf",fileType:"application/pdf",fileSize:482301,dataUrl:"",verification:"Terverifikasi"},
 {id:"DOC-2",employeeId:"EMP-001",type:"Sertifikat BLS",number:"BLS-001",issue:"2026-03-02",expiry:"2027-03-02",fileName:"BLS_Palupi.png",fileType:"image/png",fileSize:12040,dataUrl:img,verification:"Terverifikasi"},
 {id:"DOC-3",employeeId:"EMP-002",type:"SIPP",number:"SIPP-002",issue:"2025-10-01",expiry:"2026-10-01",fileName:"SIPP_Nurhayati.png",fileType:"image/png",fileSize:11000,dataUrl:img,verification:"Belum Diverifikasi"},
 {id:"DOC-4",employeeId:"EMP-005",type:"Sertifikat BTCLS",number:"BTCLS-005",issue:"2025-12-15",expiry:"2026-09-20",fileName:"BTCLS_Nia.png",fileType:"image/png",fileSize:14000,dataUrl:img,verification:"Terverifikasi"},
 {id:"DOC-5",employeeId:"EMP-004",type:"Ijazah",number:"IJZ-004",issue:"2014-07-15",expiry:"",fileName:"Ijazah_Sri.png",fileType:"image/png",fileSize:18000,dataUrl:img,verification:"Terverifikasi"}])}
 if(!localStorage.getItem(K.c))put(K.c,[{employeeId:"EMP-001",name:"Surgical Safety",level:"Kompeten",expiry:"2027-01-10"},{employeeId:"EMP-001",name:"BLS",level:"Kompeten",expiry:"2028-03-02"},{employeeId:"EMP-002",name:"PPI",level:"Kompeten",expiry:"2026-10-01"},{employeeId:"EMP-005",name:"BTCLS",level:"Supervisi",expiry:"2026-09-20"},{employeeId:"EMP-007",name:"Anestesi & Sedasi",level:"Kompeten",expiry:"2027-06-01"}]);
 if(!localStorage.getItem(K.a))put(K.a,[{employeeId:"EMP-001",type:"Scrub Nurse",level:"Mandiri",end:"2027-01-01",status:"Aktif"},{employeeId:"EMP-001",type:"Circulating Nurse",level:"Mandiri",end:"2027-01-01",status:"Aktif"},{employeeId:"EMP-002",type:"Recovery Room",level:"Dengan Supervisi",end:"2027-02-01",status:"Aktif"},{employeeId:"EMP-005",type:"Scrub Nurse",level:"Mandiri",end:"2026-12-31",status:"Review"}]);
 if(!localStorage.getItem(K.cr))put(K.cr,[{employeeId:"EMP-001",type:"Kredensial Keperawatan Kamar Operasi",submitted:"2026-01-05",status:"Aktif"},{employeeId:"EMP-002",type:"Kredensial Recovery Room",submitted:"2026-02-07",status:"Proses"},{employeeId:"EMP-005",type:"Kredensial Scrub Nurse",submitted:"2026-03-07",status:"Aktif"}]);
}
const IMPORTED_EMPLOYEE_NAMES=[
 "Anis Fitri Khoyimah, Amd. Kep","Ariani Riandy S, Amd. Kep","Bayu Doni Wicaksono, Amk",
 "Ceptian Dwi Hidayat, Amk","Dara Oktavia, Amk","Debby Sumatipang, Amk","Devy Handayani, Amk",
 "Eka Rachmat Hidayat, Amd. Kep","Fendi Warsito, Amd. Kep","Fitriadati, Amk","Fujati Fajar, Amk",
 "M. Hasbi Yusuf, Amk","M. Rahman Ansori, Amk","Melati Sari Dewi, Amk","Nia Apriliyanti, Amk",
 "Nico Teo Pratama, Amk","Ns. Ali Mafrug, S. Kep","Ns. Arifudin, S. Kep","Ns. Aris Sunandar, S. Kep",
 "Ns. Bela Novi Anggara, S. Kep","Ns. Joko, S. Kep","Ns. Maursit A. L. Raja, S. Kep",
 "Ns. Mercu Neza, S. Kep","Ns. Mustofa, S. Kep","Ns. Nafisah, S. Kep","Ns. Nurhayati, S. Kep",
 "Ns. Palupi Mardika, S. Kep","Ns. Reni Oktaria Mulyani, S. Kep","Ns. Rentawati Purba, S. Kep",
 "Ns. Riani Primaningsih, S. Kep","Ns. Sofiana Sri Nasa, S. Kep","Ns. Windo, S. Kep",
 "Nurhayati Rominar, Amk","Nurhayat, Amk","Rahmat Aprianto, Amk","Randa Septiadi, Amd. Kep",
 "Ricky Fauzi, Amk","Ridwan Agung, Amk","Selvi RAP, Amd. Kep","Sigit Purnomo, Amk",
 "Sintia Amd. Kep","Siti Nurjanah, Amk","Sri Muhyani, Amk","Sri Wulandari, Amk",
 "Suryanto, Amk","Tyas AMK","Zaki Maulana, Amk"
];
function addImportedEmployees(){
 const normalize=n=>String(n).toLowerCase().replace(/[^a-z0-9]/g,"");
 let allE=get(K.e,[]);
 allE.forEach(e=>{if(e.name==="Debby Sumat... , Amk")e.name="Debby Sumatipang, Amk"});
 allE=allE.filter((e,i,a)=>a.findIndex(x=>normalize(x.name)===normalize(e.name))===i);
 const existing=new Set(allE.map(e=>normalize(e.name)));
 let next=allE.length+1;
 IMPORTED_EMPLOYEE_NAMES.forEach(name=>{
  const key=normalize(name);
  if(existing.has(key))return;
  allE.push({id:`EMP-IMP-${String(next++).padStart(3,"0")}`,name,nip:"",profession:"Perawat",position:"Perawat Pelaksana",unit:"Kamar Operasi",status:"AKTIF",phone:"",email:"",strNumber:"",strExpiry:"",strLifetime:false,sippNumber:"",address:""});
  existing.add(key);
 });
 put(K.e,allE);
}
function sync(){
 const allE=get(K.e,[]),allD=get(K.d,[]),allC=get(K.c,[]),allA=get(K.a,[]),allCR=get(K.cr,[]);
 const employeeId=authConfig().user.employeeId;
 E=isAdmin()?allE:allE.filter(e=>e.id===employeeId);
 D=isAdmin()?allD:allD.filter(d=>d.employeeId===employeeId);
 C=isAdmin()?allC:allC.filter(c=>c.employeeId===employeeId);
 A=isAdmin()?allA:allA.filter(a=>a.employeeId===employeeId);
 CR=isAdmin()?allCR:allCR.filter(c=>c.employeeId===employeeId);
 $("#docCount").textContent=D.length;
}
if(!localStorage.getItem(AUTH_KEY))put(AUTH_KEY,defaultAuth);
seed();sync();addImportedEmployees();sync();

const views={
dashboard:()=>{let active=E.filter(e=>e.status==="AKTIF").length,exp=D.filter(d=>st(d.expiry)[0]==="EXPIRED").length,soon=D.filter(d=>["AKAN EXPIRED","SEGERA EXPIRED"].includes(st(d.expiry)[0])).length;return `<div>
<div class="head"><div><div class="eyebrow-green">OVERVIEW</div><h1 class="title">Dashboard</h1><div class="sub">Ringkasan operasional dan kelayakan SDM Kamar Operasi</div></div><div><button class="btn btn-light border me-1" onclick="go('documents')"><i class="bi bi-folder2-open me-1"></i>Document Center</button><button class="btn btn-primary admin-only" onclick="openEmployee()"><i class="bi bi-person-plus me-1"></i>Tambah Pegawai</button></div></div>
<div class="row g-3 mb-3">${[["Total Pegawai",E.length,"bi-people-fill"],["SDM Aktif",active,"bi-person-check-fill"],["Kompetensi",C.length,"bi-award-fill"],["Kewenangan",A.length,"bi-shield-check"],["Dokumen Expired",exp,"bi-file-earmark-x-fill"],["Segera Expired",soon,"bi-clock-history"]].map(x=>`<div class="col-6 col-xl-2"><div class="kpi"><div class="d-flex justify-content-between"><div class="kicon"><i class="bi ${x[2]}"></i></div><span class="kbadge">Live</span></div><div class="knum">${x[1]}</div><div class="klab">${x[0]}</div></div></div>`).join("")}</div>
<div class="row g-3"><div class="col-xl-8"><div class="panel"><div class="ph"><div><b>Komposisi SDM</b><div class="small text-muted">Distribusi berdasarkan profesi</div></div></div><div class="pb"><div class="chart"><canvas id="staffChart"></canvas></div></div></div></div><div class="col-xl-4"><div class="panel h-100"><div class="ph"><div><b>Status Dokumen</b><div class="small text-muted">Kondisi dokumen</div></div></div><div class="pb"><div class="chart"><canvas id="docChart"></canvas></div></div></div></div>
<div class="col-xl-7"><div class="panel"><div class="ph"><div><b>Dokumen Prioritas</b><div class="small text-muted">Mendekati expired</div></div><button class="btn btn-sm btn-light border" onclick="go('documents')">Semua</button></div>${priority()}</div></div>
<div class="col-xl-5"><div class="panel h-100"><div class="ph"><div><b>Aktivitas</b><div class="small text-muted">Kredensial terbaru</div></div></div><div class="pb"><div class="timeline">${CR.map(x=>`<div class="timeline-item"><b>${esc(x.type)}</b><div class="small text-muted">${esc(empName(x.employeeId))} • ${fmt(x.submitted)}</div><span class="status ${x.status==="Aktif"?"sg":"sy"} mt-1">${esc(x.status)}</span></div>`).join("")}</div></div></div></div></div></div>`},
employees:()=>`<div><div class="head"><div><div class="eyebrow-green">SDM KLINIS</div><h1 class="title">Profil Pegawai</h1><div class="sub">Master data tenaga kamar operasi</div></div><button class="btn btn-primary admin-only" onclick="openEmployee()"><i class="bi bi-person-plus me-1"></i>Tambah Pegawai</button></div><div class="panel"><div class="pb"><div class="row g-2 mb-3"><div class="col-md-5"><input id="empSearch" class="form-control" placeholder="Cari nama, NIP, profesi..." oninput="drawEmployees()"></div><div class="col-md-3"><select id="empFilter" class="form-select" onchange="drawEmployees()"><option value="">Semua Profesi</option><option>Perawat</option><option>Dokter</option><option>Penata Anestesi</option></select></div></div><div id="empTable"></div></div></div></div>`,
documents:()=>`<div><div class="head"><div><div class="eyebrow-green">DOCUMENTS</div><h1 class="title">Document Center</h1><div class="sub">Upload, preview, download, replace, dan monitoring dokumen.</div></div><button class="btn btn-primary btn-lg admin-only" onclick="openDoc()"><i class="bi bi-cloud-arrow-up me-1"></i>Upload Dokumen</button></div><div class="alert alert-success py-2"><i class="bi bi-eye-fill me-2"></i><b>Preview aktif:</b> klik ikon mata pada dokumen untuk membuka PDF/gambar langsung di viewer.</div><div class="panel"><div class="pb"><div class="row g-2 mb-3"><div class="col-lg-4"><input id="docSearch" class="form-control" placeholder="Cari dokumen / pegawai..." oninput="drawDocs()"></div><div class="col-md-3 col-lg-2"><select id="ds" class="form-select" onchange="drawDocs()"><option value="">Semua Status</option><option>AKTIF</option><option>AKAN EXPIRED</option><option>SEGERA EXPIRED</option><option>EXPIRED</option></select></div><div class="col-md-4 col-lg-3"><select id="dt" class="form-select" onchange="drawDocs()"><option value="">Semua Jenis</option>${TYPES.map(x=>`<option>${x}</option>`).join("")}</select></div></div><div id="docTable"></div></div></div></div>`,
competency:()=>`<div><div class="head"><div><div class="eyebrow-green">CLINICAL SKILLS</div><h1 class="title">Kompetensi</h1><div class="sub">Monitoring kompetensi dan masa berlaku.</div></div><button class="btn btn-primary admin-only" onclick="openRecord('competency')"><i class="bi bi-plus-lg me-1"></i>Input Kompetensi</button></div><div class="panel"><div class="pb"><div class="table-responsive"><table class="table"><thead><tr><th>Kompetensi</th><th>Pegawai</th><th>Level</th><th>Expired</th><th>Status</th><th>Aksi</th></tr></thead><tbody>${C.map(c=>`<tr><td><b>${esc(c.name)}</b></td><td>${esc(empName(c.employeeId))}</td><td>${esc(c.level)}</td><td>${fmt(c.expiry)}</td><td><span class="status ${c.status?({Aktif:"sg","Review":"sy","Tidak Aktif":"sr"}[c.status]||"sy"):st(c.expiry)[1]}">${esc(c.status||st(c.expiry)[0])}</span></td><td>${recordActions("competency",c)}</td></tr>`).join("")}</tbody></table></div></div></div></div>`,
authority:()=>`<div><div class="head"><div><div class="eyebrow-green">CLINICAL GOVERNANCE</div><h1 class="title">Kewenangan Klinis</h1><div class="sub">Kewenangan, level dan masa berlaku.</div></div><button class="btn btn-primary admin-only" onclick="openRecord('authority')"><i class="bi bi-plus-lg me-1"></i>Input Kewenangan</button></div><div class="panel"><div class="pb"><div class="table-responsive"><table class="table"><thead><tr><th>Pegawai</th><th>Kewenangan</th><th>Level</th><th>Berlaku</th><th>Status</th><th>Aksi</th></tr></thead><tbody>${A.map(a=>`<tr><td>${esc(empName(a.employeeId))}</td><td>${esc(a.type)}</td><td>${esc(a.level)}</td><td>${fmt(a.end)}</td><td><span class="status ${a.status==="Aktif"?"sg":"sy"}">${esc(a.status)}</span></td><td>${recordActions("authority",a)}</td></tr>`).join("")}</tbody></table></div></div></div></div>`,
credentials:()=>`<div><div class="head"><div><div class="eyebrow-green">CREDENTIALING</div><h1 class="title">Kredensial</h1><div class="sub">Workflow dan status penetapan.</div></div><button class="btn btn-primary admin-only" onclick="openRecord('credentials')"><i class="bi bi-plus-lg me-1"></i>Input Kredensial</button></div><div class="panel"><div class="pb">${CR.map(c=>`<div class="doc-card mb-2 d-flex justify-content-between align-items-center"><div><b>${esc(c.type)}</b><div class="small text-muted">${esc(empName(c.employeeId))} • ${fmt(c.submitted)}</div></div><div class="d-flex align-items-center gap-2"><span class="status ${c.status==="Aktif"?"sg":"sy"}">${esc(c.status)}</span>${recordActions("credentials",c)}</div></div>`).join("")}</div></div></div>`,
cv:()=>`<div><div class="head"><div><div class="eyebrow-green">STAFF PROFILE</div><h1 class="title">CV & Riwayat</h1><div class="sub">Pilih pegawai untuk melihat profil terintegrasi.</div></div></div><div class="panel"><div class="pb">${E.map(e=>`<div class="doc-card mb-2 d-flex justify-content-between align-items-center"><div class="d-flex align-items-center gap-3"><span class="mini">${ini(e.name)}</span><div><b>${esc(e.name)}</b><div class="small text-muted">${esc(e.profession)} • ${esc(e.position||"-")}</div></div></div><button class="btn btn-sm btn-light border" onclick="employeeDetail('${e.id}')">Lihat Profil</button></div>`).join("")}</div></div></div>`,
matrix:()=>{let sk=["Scrub Nurse","Circulating Nurse","Recovery Room","PPI","BLS","BTCLS"];return `<div><div class="head"><div><div class="eyebrow-green">COMPETENCY MAP</div><h1 class="title">Matriks Kompetensi</h1><div class="sub">✓ kompeten • S supervisi • ✕ belum kompeten</div></div></div><div class="panel"><div class="pb"><div class="table-responsive"><table class="table"><thead><tr><th>Pegawai</th>${sk.map(s=>`<th>${s}</th>`).join("")}</tr></thead><tbody>${E.map(e=>`<tr><td><b>${esc(e.name)}</b></td>${sk.map(s=>{let a=A.find(x=>x.employeeId===e.id&&x.type===s),c=C.find(x=>x.employeeId===e.id&&x.name===s);let v=a?.level==="Mandiri"||c?.level==="Kompeten"?"✓":a?.level==="Dengan Supervisi"||c?.level==="Supervisi"?"S":(a||c)?"✕":"—";return`<td style="text-align:center;font-weight:800" class="${v==="✓"?"text-success":v==="S"?"text-warning":v==="✕"?"text-danger":"text-muted"}">${v}</td>`}).join("")}</tr>`).join("")}</tbody></table></div></div></div></div>`},
assignments:()=>`<div><div class="head"><div><div class="eyebrow-green">OPERATING ROOM</div><h1 class="title">Penugasan OK</h1><div class="sub">Roster contoh shift Kamar Operasi.</div></div><button class="btn btn-primary" onclick="Swal.fire('Modul roster','Siap dikembangkan menjadi kalender/draggable roster.','info')">Tambah Penugasan</button></div><div class="row g-3">${["OK 1","OK 2","OK 3","OK 4"].map(r=>`<div class="col-xl-6"><div class="doc-card"><div class="d-flex justify-content-between"><b><span class="status sg">${r}</span> Shift Pagi</b><span class="small text-muted">07.00–14.00</span></div><div class="row g-2 mt-2 small"><div class="col-6"><span class="text-muted">Dokter Bedah</span><div>dr. Hendar, Sp.OT</div></div><div class="col-6"><span class="text-muted">Anestesi</span><div>dr. Eva, Sp.An</div></div><div class="col-6"><span class="text-muted">Scrub</span><div>Ns. Palupi Mardika</div></div><div class="col-6"><span class="text-muted">Sirkuler</span><div>Ns. Nurhayati</div></div></div></div></div>`).join("")}</div></div>`,
monitoring:()=>{let e=D.filter(d=>st(d.expiry)[0]==="EXPIRED").length,s=D.filter(d=>["AKAN EXPIRED","SEGERA EXPIRED"].includes(st(d.expiry)[0])).length,v=D.filter(d=>d.verification!=="Terverifikasi").length;return `<div><div class="head"><div><div class="eyebrow-green">CONTROL CENTER</div><h1 class="title">Monitoring</h1><div class="sub">Pusat perhatian dokumen dan kelayakan SDM.</div></div></div><div class="row g-3"><div class="col-md-4"><div class="kpi"><div class="kicon"><i class="bi bi-file-earmark-x"></i></div><div class="knum">${e}</div><div class="klab">Dokumen Expired</div></div></div><div class="col-md-4"><div class="kpi"><div class="kicon"><i class="bi bi-clock-history"></i></div><div class="knum">${s}</div><div class="klab">Segera Expired</div></div></div><div class="col-md-4"><div class="kpi"><div class="kicon"><i class="bi bi-patch-check"></i></div><div class="knum">${v}</div><div class="klab">Belum Terverifikasi</div></div></div></div></div>`},
reports:()=>`<div><div class="head"><div><div class="eyebrow-green">REPORTS</div><h1 class="title">Laporan</h1><div class="sub">Export data master pegawai dan ringkasan dokumen.</div></div><button class="btn btn-primary" onclick="exportCSV()"><i class="bi bi-filetype-csv me-1"></i>Export Pegawai</button></div><div class="row g-3">${[["Pegawai",E.length],["Kompetensi",C.length],["Kewenangan",A.length],["Dokumen",D.length]].map(x=>`<div class="col-6 col-xl-3"><div class="kpi"><div class="knum">${x[1]}</div><div class="klab">${x[0]}</div></div></div>`).join("")}</div></div>`,
settings:()=>{let auth=authConfig(),account=isAdmin()?auth.admin:auth.user;return `<div><div class="head"><div><div class="eyebrow-green">SYSTEM</div><h1 class="title">Settings</h1><div class="sub">Pengaturan akun ${isAdmin()?"Admin":"User"}.</div></div></div><div class="panel"><div class="pb"><form id="accountForm" class="row g-3"><div class="col-md-6"><label class="form-label">Nama</label><input id="accountName" class="form-control" value="${esc(account.name)}" required></div><div class="col-md-6"><label class="form-label">Username</label><input id="accountUsername" class="form-control" value="${esc(account.username)}" required></div>${isAdmin()?"":`<div class="col-md-6"><label class="form-label">Pegawai User</label><select id="accountEmployee" class="form-select">${get(K.e,[]).map(e=>`<option value="${e.id}" ${e.id===auth.user.employeeId?"selected":""}>${esc(e.name)}</option>`).join("")}</select></div>`}<div class="col-md-6"><label class="form-label">Password Baru</label><input id="accountPassword" type="password" class="form-control" placeholder="Kosongkan jika tidak diubah"></div><div class="col-12"><button class="btn btn-primary" type="submit">Simpan Pengaturan</button></div></form></div></div></div>`},
"user-management":()=>{let auth=authConfig(),users=auth.users||[];return `<div><div class="head"><div><div class="eyebrow-green">ACCESS CONTROL</div><h1 class="title">Manajemen User</h1><div class="sub">Kelola akun user dan pegawai yang dapat mereka akses.</div></div><button class="btn btn-primary" onclick="manageUser()"><i class="bi bi-person-plus me-1"></i>Tambah User</button></div><div class="panel"><div class="pb"><div class="table-responsive"><table class="table"><thead><tr><th>Nama</th><th>Username</th><th>Pegawai</th><th>Aksi</th></tr></thead><tbody>${users.map(u=>`<tr><td><b>${esc(u.name)}</b></td><td>${esc(u.username)}</td><td>${esc(empName(u.employeeId))}</td><td><button class="action me-1" onclick="manageUser('${esc(u.username)}')" title="Edit"><i class="bi bi-pencil"></i></button><button class="action" onclick="removeUser('${esc(u.username)}')" title="Hapus"><i class="bi bi-trash"></i></button></td></tr>`).join("")||`<tr><td colspan="4" class="text-muted">Belum ada user.</td></tr>`}</tbody></table></div></div></div></div>`}
};

function priority(){let r=[...D].filter(d=>["EXPIRED","AKAN EXPIRED","SEGERA EXPIRED"].includes(st(d.expiry)[0])).sort((a,b)=>(day(a.expiry)??99999)-(day(b.expiry)??99999)).slice(0,6);return `<div class="pb p-0">${r.length?`<div class="table-responsive"><table class="table mb-0"><thead><tr><th>Dokumen</th><th>Pegawai</th><th>Expired</th><th>Status</th><th></th></tr></thead><tbody>${r.map(d=>`<tr><td><b>${esc(d.type)}</b><div class="small text-muted">${esc(d.fileName)}</div></td><td>${esc(empName(d.employeeId))}</td><td>${fmt(d.expiry)}</td><td><span class="status ${st(d.expiry)[1]}">${st(d.expiry)[0]}</span></td><td><button class="action" onclick="preview('${d.id}')"><i class="bi bi-eye"></i></button></td></tr>`).join("")}</tbody></table></div>`:`<div class="empty">Tidak ada dokumen prioritas.</div>`}</div>`}

function updateAccountUi(){let auth=authConfig(),account=isAdmin()?auth.admin:auth.user;document.body.dataset.role=currentRole;$(".profile b").textContent=account.name;$(".profile small").textContent=isAdmin()?"Admin":"User";$(".avatar").textContent=ini(account.name)}
function manageUser(username=""){if(!isAdmin())return;let auth=authConfig(),user=(auth.users||[]).find(u=>u.username===username)||{name:"",username:"",password:"",employeeId:""};let options=get(K.e,[]).map(e=>`<option value="${e.id}" ${e.id===user.employeeId?"selected":""}>${esc(e.name)}</option>`).join("");Swal.fire({title:username?"Edit User":"Tambah User",html:`<input id="userName" class="swal2-input" placeholder="Nama" value="${esc(user.name)}"><input id="userUsername" class="swal2-input" placeholder="Username" value="${esc(user.username)}"><input id="userPassword" type="password" class="swal2-input" placeholder="${username?"Password baru (opsional)":"Password"}"><select id="userEmployee" class="swal2-select"><option value="">Pilih pegawai</option>${options}</select>`,showCancelButton:true,confirmButtonText:"Simpan",preConfirm:()=>({name:$("#userName").value.trim(),username:$("#userUsername").value.trim(),password:$("#userPassword").value,employeeId:$("#userEmployee").value})}).then(r=>{if(!r.isConfirmed)return;let v=r.value;if(!v.name||!v.username||(!username&&!v.password)){Swal.fire("Data belum lengkap","Nama, username, dan password wajib diisi.","warning");return}if(v.username!==username&&((auth.admin&&auth.admin.username===v.username)||(auth.users||[]).some(u=>u.username===v.username))){Swal.fire("Gagal","Username sudah digunakan.","error");return}let list=(auth.users||[]).filter(u=>u.username!==username);list.push({...user,...v,password:v.password||user.password});auth.users=list;saveAuth(auth);go("user-management")})}
function removeUser(username){if(!isAdmin())return;Swal.fire({title:"Hapus user?",text:"Akun tidak dapat digunakan lagi setelah dihapus.",icon:"warning",showCancelButton:true,confirmButtonText:"Hapus",cancelButtonText:"Batal"}).then(r=>{if(!r.isConfirmed)return;let auth=authConfig();auth.users=(auth.users||[]).filter(u=>u.username!==username);saveAuth(auth);go("user-management")})}
function bindAccountForm(){let form=$("#accountForm");if(!form)return;form.onsubmit=e=>{e.preventDefault();let auth=authConfig(),account=isAdmin()?auth.admin:auth.user;account.name=$("#accountName").value.trim();account.username=$("#accountUsername").value.trim();if($("#accountPassword").value)account.password=$("#accountPassword").value;if(!isAdmin())auth.user.employeeId=$("#accountEmployee").value;auth[isAdmin()?"admin":"user"]=account;put(AUTH_KEY,auth);updateAccountUi();Swal.fire({toast:true,position:"top-end",timer:1800,showConfirmButton:false,icon:"success",title:"Pengaturan tersimpan"})}}
function go(v){if(!isAdmin()&&(v==="reports"||v==="user-management"))v="dashboard";sync();$$(".nav-link").forEach(x=>x.classList.toggle("active",x.dataset.view===v));$("#crumb").textContent=({dashboard:"Dashboard",employees:"Profil Pegawai",cv:"CV & Riwayat",competency:"Kompetensi",authority:"Kewenangan Klinis",credentials:"Kredensial",documents:"Document Center",matrix:"Matriks Kompetensi",assignments:"Penugasan OK",monitoring:"Monitoring",reports:"Laporan","user-management":"Manajemen User",settings:"Settings"})[v];$("#content").innerHTML=views[v]();bindAccountForm();updateAccountUi();if(v==="dashboard")charts();if(v==="employees")drawEmployees();if(v==="documents")drawDocs();if(innerWidth<992)$("#side").classList.remove("mobile")}
function recordActions(type,item){let id=item.id||`${type}-${item.employeeId||""}-${item.name||item.type||""}`.replace(/\W/g,"-");return `<div class="d-flex gap-1"><button class="action" title="View" onclick="openRecord('${type}','${esc(id)}','view')"><i class="bi bi-eye"></i></button><button class="action admin-only" title="Edit" onclick="openRecord('${type}','${esc(id)}')"><i class="bi bi-pencil"></i></button><button class="action text-danger admin-only" title="Hapus" onclick="deleteRecord('${type}','${esc(id)}')"><i class="bi bi-trash"></i></button></div>`}
function recordStore(type){return type==="competency"?C:type==="authority"?A:CR}
function recordId(type,item){return item.id||(item.id=`${type}-${item.employeeId||""}-${item.name||item.type||""}`.replace(/\W/g,"-"))}
function openRecord(type,id="",mode="edit"){
 sync();let list=recordStore(type),item=list.find(x=>recordId(type,x)===id)||{},isView=mode==="view";
 let fields=type==="competency"?[
  ["name","Nama Kompetensi","text"],["employeeId","Pegawai","employee"],["level","Level","select",["Kompeten","Supervisi","Belum Kompeten"]],["expiry","Masa Berlaku","date"],["status","Status","select",["Aktif","Review","Tidak Aktif"]]
 ]:type==="authority"?[
  ["employeeId","Pegawai","employee"],["type","Kewenangan","text"],["level","Level","select",["Mandiri","Dengan Supervisi","Tidak Berwenang"]],["end","Berlaku Sampai","date"],["status","Status","select",["Aktif","Review","Tidak Aktif"]]
 ]:[
  ["employeeId","Pegawai","employee"],["type","Jenis Kredensial","text"],["level","Level","select",["Kompeten","Supervisi","Belum Kompeten"]],["submitted","Tanggal Pengajuan","date"],["status","Status","select",["Aktif","Proses","Review","Ditolak"]]
 ];
 let html=fields.map(([key,label,input,options])=>input==="employee"?`<label class="form-label text-start d-block">${label}</label><select id="record-${key}" class="form-select mb-2">${E.map(e=>`<option value="${e.id}" ${item[key]===e.id?"selected":""}>${esc(e.name)}</option>`).join("")}</select>`:input==="select"?`<label class="form-label text-start d-block">${label}</label><select id="record-${key}" class="form-select mb-2"><option value="">Pilih ${label}</option>${options.map(option=>`<option value="${esc(option)}" ${item[key]===option?"selected":""}>${esc(option)}</option>`).join("")}</select>`:`<label class="form-label text-start d-block">${label}</label><input id="record-${key}" type="${input}" class="form-control mb-2" value="${esc(item[key]||"")}">`).join("");
 if(isView){html=fields.map(([key,label])=>`<div class="d-flex justify-content-between border-bottom py-2"><b>${label}</b><span>${esc(key==="employeeId"?empName(item[key]):item[key]||"-")}</span></div>`).join("")}
 Swal.fire({title:isView?"Detail Data":(id?"Edit Data":"Input Data"),html,showConfirmButton:!isView,showCancelButton:true,confirmButtonText:"Simpan",cancelButtonText:"Tutup",focusConfirm:false,preConfirm:()=>{if(isView)return true;let next={...item};fields.forEach(([key])=>next[key]=$("#record-"+key).value);return next}}).then(r=>{if(!r.isConfirmed||isView)return;let next=r.value;recordId(type,next);if(id){let i=list.findIndex(x=>recordId(type,x)===id);if(i>=0)list[i]=next}else list.push(next);put(type==="competency"?K.c:type==="authority"?K.a:K.cr,list);go(type)});
}
function deleteRecord(type,id){Swal.fire({title:"Hapus data ini?",icon:"warning",showCancelButton:true,confirmButtonText:"Hapus",cancelButtonText:"Batal"}).then(r=>{if(!r.isConfirmed)return;let list=recordStore(type);list.splice(list.findIndex(x=>recordId(type,x)===id),1);put(type==="competency"?K.c:type==="authority"?K.a:K.cr,list);go(type)})}
function charts(){new Chart($("#staffChart"),{type:"bar",data:{labels:["Perawat","Dokter","Penata Anestesi","Administrasi"],datasets:[{data:["Perawat","Dokter","Penata Anestesi","Administrasi"].map(p=>E.filter(e=>e.profession===p).length),borderRadius:7}]},options:{maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{y:{beginAtZero:true,ticks:{stepSize:1}}}}});let l=["Aktif","Akan Expired","Segera Expired","Expired"],v=l.map(x=>D.filter(d=>st(d.expiry)[0]===x).length);new Chart($("#docChart"),{type:"doughnut",data:{labels:l,datasets:[{data:v}]},options:{maintainAspectRatio:false,cutout:"68%",plugins:{legend:{position:"bottom"}}}})}
function drawEmployees(){let q=($("#empSearch")?.value||"").toLowerCase(),f=$("#empFilter")?.value||"";let r=E.filter(e=>(!q||[e.name,e.nip,e.profession,e.position,e.unit].join(" ").toLowerCase().includes(q))&&(!f||e.profession===f));$("#empTable").innerHTML=`<div class="table-responsive"><table class="table"><thead><tr><th>Pegawai</th><th>Profesi</th><th>Jabatan</th><th>Unit</th><th>Status</th><th>Aksi</th></tr></thead><tbody>${r.map(e=>`<tr><td><div class="d-flex align-items-center gap-2"><span class="mini">${ini(e.name)}</span><div><button class="btn btn-link p-0 text-decoration-none fw-semibold" onclick="employeeDetail('${e.id}')">${esc(e.name)}</button><div class="small text-muted">${esc(e.nip)}</div></div></div></td><td>${esc(e.profession)}</td><td>${esc(e.position||"-")}</td><td>${esc(e.unit||"-")}</td><td><span class="status ${e.status==="AKTIF"?"sg":"sr"}">${e.status}</span></td><td><button class="action me-1" onclick="openEmployee('${e.id}')"><i class="bi bi-pencil"></i></button><button class="action" onclick="delEmp('${e.id}')"><i class="bi bi-trash"></i></button></td></tr>`).join("")}</tbody></table></div>`}
function drawDocs(){let q=($("#docSearch")?.value||"").toLowerCase(),f=$("#ds")?.value||"",t=$("#dt")?.value||"";let r=D.filter(d=>{let s=st(d.expiry)[0];return(!q||[d.type,d.fileName,d.number,empName(d.employeeId)].join(" ").toLowerCase().includes(q))&&(!f||s===f)&&(!t||d.type===t)});$("#docTable").innerHTML=r.length?`<div class="table-responsive"><table class="table"><thead><tr><th>Dokumen</th><th>Pegawai</th><th>Nomor</th><th>Expired</th><th>Status</th><th>Verifikasi</th><th>Aksi</th></tr></thead><tbody>${r.map(d=>`<tr><td><b>${esc(d.type)}</b><div class="small text-muted">${esc(d.fileName||"Tanpa file")} • ${bytes(d.fileSize)}</div></td><td>${esc(empName(d.employeeId))}</td><td>${esc(d.number||"-")}</td><td>${fmt(d.expiry)}</td><td><span class="status ${st(d.expiry)[1]}">${st(d.expiry)[0]}</span></td><td><span class="status ${d.verification==="Terverifikasi"?"sg":"sy"}">${esc(d.verification||"Belum Diverifikasi")}</span></td><td><button class="action me-1" title="View" onclick="preview('${d.id}')"><i class="bi bi-eye"></i></button><button class="action me-1" title="Replace/Edit" onclick="openDoc('${d.id}')"><i class="bi bi-arrow-repeat"></i></button><button class="action" title="Delete" onclick="delDoc('${d.id}')"><i class="bi bi-trash"></i></button></td></tr>`).join("")}</tbody></table></div>`:`<div class="empty"><i class="bi bi-folder-x d-block fs-1"></i>Belum ada dokumen.</div>`}
function openEmployee(id=""){if(!isAdmin())return;let e=E.find(x=>x.id===id);$("#empForm").reset();$("#empId").value=e?.id||"";if(e){$("#empName").value=e.name;$("#empNip").value=e.nip;$("#empProf").value=e.profession;$("#empPos").value=e.position||"";$("#empUnit").value=e.unit||"";$("#empStatus").value=["PNS","Non-PNS","PPPK","PPPK PW"].includes(e.status)?e.status:"PNS";$("#empPhone").value=e.phone||"";$("#empEmail").value=e.email||"";$("#empStr").value=e.strNumber||"";$("#empStrExpiry").value=e.strExpiry||"";$("#empStrLifetime").checked=!!e.strLifetime;$("#empStrExpiry").disabled=!!e.strLifetime;$("#empSipp").value=e.sippNumber||e.license||"";$("#empAddr").value=e.address||""}new bootstrap.Modal("#empModal").show()}
function delEmp(id){if(!isAdmin())return;Swal.fire({title:"Hapus pegawai?",icon:"warning",showCancelButton:true,confirmButtonText:"Hapus"}).then(r=>{if(r.isConfirmed){E=E.filter(e=>e.id!==id);put(K.e,E);go("employees")}})}
function employeeDetail(id){let e=E.find(x=>x.id===id),docs=D.filter(d=>d.employeeId===id);$("#content").innerHTML=`<div class="head"><div><button class="btn btn-light border mb-2" onclick="go('employees')"><i class="bi bi-arrow-left me-1"></i>Kembali</button><div class="eyebrow-green">STAFF PROFILE</div><h1 class="title">${esc(e.name)}</h1><div class="sub">${esc(e.profession)} • ${esc(e.position||"-")} • ${esc(e.unit||"-")}</div></div><button class="btn btn-primary" onclick="openDoc('', '${e.id}')"><i class="bi bi-cloud-arrow-up me-1"></i>Upload Dokumen</button></div><div class="panel mb-3"><div class="pb"><div class="d-flex flex-wrap align-items-center gap-3"><span class="avatar" style="width:70px;height:70px;font-size:18px">${ini(e.name)}</span><div class="flex-grow-1"><h4>${esc(e.name)}</h4><div class="text-muted">${esc(e.nip)}</div><span class="status sg mt-2">${e.status}</span></div><div style="min-width:230px"><div class="d-flex justify-content-between small"><span>Kelengkapan</span><b>88%</b></div><div class="progress"><div class="progress-bar bg-success" style="width:88%"></div></div></div></div></div></div><ul class="nav nav-pills mb-3"><li class="nav-item"><button class="nav-link active" onclick="detailTab(this,'profile','${id}')">Profil</button></li><li class="nav-item"><button class="nav-link" onclick="detailTab(this,'documents','${id}')">Dokumen (${docs.length})</button></li><li class="nav-item"><button class="nav-link" onclick="detailTab(this,'competency','${id}')">Kompetensi</button></li><li class="nav-item"><button class="nav-link" onclick="detailTab(this,'authority','${id}')">Kewenangan</button></li></ul><div id="detailBody">${profile(e)}</div>`}
function profile(e){let str=e.strNumber||"-",strValidity=e.strLifetime?"Seumur hidup":e.strExpiry?fmt(e.strExpiry):"-";return `<div class="panel"><div class="pb"><div class="row g-4">${[["NIP",e.nip],["Profesi",e.profession],["Jabatan",e.position],["Unit",e.unit],["No. HP",e.phone],["Email",e.email],["Nomor STR",str],["Masa Aktif STR",strValidity],["Nomor SIPP",e.sippNumber||e.license||"-"],["Alamat",e.address||"-"]].map(x=>`<div class="col-md-3"><div class="small text-muted">${x[0]}</div><b>${esc(x[1]||"-")}</b></div>`).join("")}</div></div></div>`}
function detailTab(btn,t,id){$$(".nav-pills .nav-link").forEach(x=>x.classList.remove("active"));btn.classList.add("active");let e=E.find(x=>x.id===id),docs=D.filter(d=>d.employeeId===id),comp=C.filter(c=>c.employeeId===id),auth=A.filter(a=>a.employeeId===id);if(t==="profile")$("#detailBody").innerHTML=profile(e);if(t==="documents")$("#detailBody").innerHTML=`<div class="panel"><div class="ph"><b>Dokumen Digital</b><button class="btn btn-sm btn-primary" onclick="openDoc('','${id}')"><i class="bi bi-cloud-arrow-up me-1"></i>Upload</button></div><div class="pb">${docs.length?docs.map(d=>`<div class="doc-card mb-2 d-flex align-items-center gap-3"><span class="kicon"><i class="bi bi-file-earmark-text"></i></span><div class="flex-grow-1"><b>${esc(d.type)}</b><div class="small text-muted">${esc(d.fileName)}</div><span class="status ${st(d.expiry)[1]}">${st(d.expiry)[0]}</span></div><button class="action" onclick="preview('${d.id}')"><i class="bi bi-eye"></i></button></div>`).join(""):`<div class="empty">Belum ada dokumen.</div>`}</div></div>`;if(t==="competency")$("#detailBody").innerHTML=`<div class="panel"><div class="pb"><div class="table-responsive"><table class="table"><thead><tr><th>Kompetensi</th><th>Level</th><th>Expired</th><th>Status</th></tr></thead><tbody>${comp.map(c=>`<tr><td>${esc(c.name)}</td><td>${esc(c.level)}</td><td>${fmt(c.expiry)}</td><td><span class="status ${st(c.expiry)[1]}">${st(c.expiry)[0]}</span></td></tr>`).join("")}</tbody></table></div></div></div>`;if(t==="authority")$("#detailBody").innerHTML=`<div class="panel"><div class="pb"><div class="table-responsive"><table class="table"><thead><tr><th>Kewenangan</th><th>Level</th><th>Berlaku</th><th>Status</th></tr></thead><tbody>${auth.map(a=>`<tr><td>${esc(a.type)}</td><td>${esc(a.level)}</td><td>${fmt(a.end)}</td><td><span class="status ${a.status==="Aktif"?"sg":"sy"}">${esc(a.status)}</span></td></tr>`).join("")}</tbody></table></div></div></div>`}
function openDoc(editId="",employeeId=""){fileSel=null;$("#docForm").reset();$("#docId").value="";$("#fileInfo").innerHTML="";$("#livePreview").className="empty-preview";$("#livePreview").innerHTML='<i class="bi bi-file-earmark-text"></i><div>Preview akan tampil di sini</div>';$("#docEmp").innerHTML=E.map(e=>`<option value="${e.id}">${esc(e.name)}</option>`).join("");$("#docType").innerHTML=TYPES.map(x=>`<option>${x}</option>`).join("");if(employeeId)$("#docEmp").value=employeeId;let d=D.find(x=>x.id===editId);if(d){$("#docId").value=d.id;$("#docEmp").value=d.employeeId;$("#docType").value=d.type;$("#docNo").value=d.number||"";$("#docIssue").value=d.issue||"";$("#docExp").value=d.expiry||"";$("#docNotes").value=d.notes||"";$("#fileInfo").innerHTML=`<div class="alert alert-light border">${esc(d.fileName)} • ${bytes(d.fileSize)}</div>`;if(d.dataUrl)showPreview(d.dataUrl,d.fileType)}new bootstrap.Modal("#docModal").show()}
function pickFile(f){if(!f)return;if(f.size>10*1024*1024){Swal.fire("File terlalu besar","Maksimum 10 MB.","error");return}if(!/\.(pdf|jpg|jpeg|png|doc|docx|xls|xlsx)$/i.test(f.name)){Swal.fire("Format tidak didukung","Gunakan PDF, JPG, PNG, DOC, DOCX, XLS atau XLSX.","error");return}fileSel=f;$("#fileInfo").innerHTML=`<div class="alert alert-success">${esc(f.name)} • ${bytes(f.size)}</div>`;showPreview(URL.createObjectURL(f),f.type)}
function showPreview(url,type){$("#livePreview").className="";$("#livePreview").innerHTML=type==="application/pdf"?`<iframe class="live-pdf" src="${url}"></iframe>`:type?.startsWith("image/")?`<img class="live-img" src="${url}">`:`<div class="empty-preview"><i class="bi bi-file-earmark-text"></i><div>Format ini tidak dirender. File siap disimpan.</div></div>`}
function saveFile(f){return new Promise((res,rej)=>{let r=new FileReader;r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(f)})}
function preview(id){let d=D.find(x=>x.id===id);if(!d)return;$("#viewerTitle").textContent=d.type;$("#viewerMeta").textContent=`${empName(d.employeeId)} • ${d.fileName}`;$("#viewerBody").innerHTML=d.dataUrl?(d.fileType==="application/pdf"?`<iframe src="${d.dataUrl}"></iframe>`:d.fileType?.startsWith("image/")?`<img src="${d.dataUrl}">`:`<div class="viewer-file"><i class="bi bi-file-earmark-text fs-1 text-success"></i><h5 class="mt-3">${esc(d.fileName)}</h5><div>Gunakan Download untuk membuka file.</div></div>`):`<div class="viewer-file"><i class="bi bi-file-earmark-x fs-1 text-warning"></i><h5 class="mt-3">Preview tidak tersedia</h5><div>Gunakan Replace untuk mengunggah file.</div></div>`;$("#downloadBtn").onclick=()=>downloadDoc(id);new bootstrap.Modal("#viewer").show()}
function downloadDoc(id){let d=D.find(x=>x.id===id);if(!d?.dataUrl){Swal.fire("File tidak tersedia","File asli belum tersedia.","info");return}let a=document.createElement("a");a.href=d.dataUrl;a.download=d.fileName||"dokumen";a.click()}
function delDoc(id){Swal.fire({title:"Hapus dokumen?",icon:"warning",showCancelButton:true,confirmButtonText:"Hapus"}).then(r=>{if(r.isConfirmed){D=D.filter(d=>d.id!==id);put(K.d,D);go("documents")}})}
function exportCSV(){let rows=[["ID","Nama","NIP","Profesi","Jabatan","Unit","Status"],...E.map(e=>[e.id,e.name,e.nip,e.profession,e.position,e.unit,e.status])];let csv=rows.map(r=>r.map(v=>`"${String(v??"").replace(/"/g,'""')}"`).join(",")).join("\\n");let a=document.createElement("a");a.href=URL.createObjectURL(new Blob(["\\ufeff"+csv],{type:"text/csv;charset=utf-8"}));a.download="SIM-KOJA_V2_Pegawai.csv";a.click()}
$("#eye").onclick=()=>{$("#p").type=$("#p").type==="password"?"text":"password";$("#eye i").className=$("#p").type==="password"?"bi bi-eye":"bi bi-eye-slash"};
$("#logout").onclick=()=>{sessionStorage.removeItem(SESSION_KEY);sessionStorage.removeItem("simkoja_role");sessionStorage.removeItem("simkoja_username");location.reload()};$("#logout2").onclick=()=>{sessionStorage.removeItem(SESSION_KEY);sessionStorage.removeItem("simkoja_role");sessionStorage.removeItem("simkoja_username");location.reload()};
$("#pin").onclick=()=>$("#side").classList.toggle("collapsed");$("#mobile").onclick=()=>$("#side").classList.toggle("mobile");
document.addEventListener("click",e=>{let b=e.target.closest("[data-view]");if(b)go(b.dataset.view)});
$("#search").onkeydown=e=>{if(e.key==="Enter"&&e.target.value.trim()){go("employees");setTimeout(()=>{$("#empSearch").value=e.target.value;drawEmployees()},30)}};
$("#quick").onclick=()=>openDoc();
$("#notif").onclick=()=>{let n=D.filter(d=>["EXPIRED","AKAN EXPIRED","SEGERA EXPIRED"].includes(st(d.expiry)[0]));Swal.fire({title:"Notification Center",html:n.length?n.map(d=>`<div class="text-start border-bottom py-2"><b>${esc(d.type)}</b><br><small>${esc(empName(d.employeeId))} • ${fmt(d.expiry)} • ${st(d.expiry)[0]}</small></div>`).join(""):"Tidak ada notifikasi.",confirmButtonText:"Tutup"})};
$("#empForm").onsubmit=e=>{e.preventDefault();let id=$("#empId").value||"EMP-"+Date.now(),o={id,name:$("#empName").value.trim(),nip:$("#empNip").value.trim(),profession:$("#empProf").value,position:$("#empPos").value.trim(),unit:$("#empUnit").value.trim(),status:$("#empStatus").value,phone:$("#empPhone").value.trim(),email:$("#empEmail").value.trim(),strNumber:$("#empStr").value.trim(),strExpiry:$("#empStrExpiry").value,strLifetime:$("#empStrLifetime").checked,sippNumber:$("#empSipp").value.trim(),address:$("#empAddr").value.trim()},i=E.findIndex(x=>x.id===id);i>=0?E[i]=o:E.push(o);put(K.e,E);bootstrap.Modal.getInstance($("#empModal")).hide();go("employees")};
$("#empStrLifetime").onchange=e=>{$("#empStrExpiry").disabled=e.target.checked;if(e.target.checked)$("#empStrExpiry").value=""};
$("#pick").onclick=()=>$("#file").click();$("#file").onchange=e=>pickFile(e.target.files[0]);
["dragenter","dragover"].forEach(x=>$("#drop").addEventListener(x,e=>{e.preventDefault();$("#drop").classList.add("drag")}));["dragleave","drop"].forEach(x=>$("#drop").addEventListener(x,e=>{e.preventDefault();$("#drop").classList.remove("drag")}));$("#drop").ondrop=e=>pickFile(e.dataTransfer.files[0]);
$("#docForm").onsubmit=async e=>{e.preventDefault();let old=D.find(d=>d.id===$("#docId").value);if(!old&&!fileSel){Swal.fire("File belum dipilih","Silakan pilih atau drop file.","warning");return}let data=old?.dataUrl||"",name=old?.fileName||"",type=old?.fileType||"",size=old?.fileSize||0;if(fileSel){data=await saveFile(fileSel);name=fileSel.name;type=fileSel.type;size=fileSel.size}let o={id:old?.id||"DOC-"+Date.now(),employeeId:$("#docEmp").value,type:$("#docType").value,number:$("#docNo").value.trim(),issue:$("#docIssue").value,expiry:$("#docExp").value,fileName:name,fileType:type,fileSize:size,dataUrl:data,verification:old?.verification||"Belum Diverifikasi",notes:$("#docNotes").value};let i=D.findIndex(d=>d.id===o.id);i>=0?D[i]=o:D.push(o);put(K.d,D);bootstrap.Modal.getInstance($("#docModal")).hide();go("documents");Swal.fire({toast:true,position:"top-end",timer:2000,showConfirmButton:false,icon:"success",title:i>=0?"Dokumen diperbarui":"Dokumen berhasil diunggah"})};
$("#dateNow").textContent=new Date().toLocaleDateString("id-ID",{day:"2-digit",month:"long",year:"numeric"});

// Login handler (supports admin and user stored in AUTH_KEY)
$("#loginForm").onsubmit = e => {
  e.preventDefault();
  const auth = authConfig();
  const username = $("#u").value.trim();
  const password = $("#p").value;
  const role = auth.admin?.username === username && auth.admin.password === password ? "admin" : (auth.users||[]).some(u=>u.username===username&&u.password===password) ? "user" : "";
  if (role) {
    currentRole = role;
    currentUsername = username;
    sessionStorage.setItem(SESSION_KEY, "1");
    sessionStorage.setItem("simkoja_role", role);
    sessionStorage.setItem("simkoja_username", username);
    $("#login").classList.add("d-none");
    $("#app").classList.remove("d-none");
    updateAccountUi();
    go("dashboard");
  } else {
    Swal.fire("Login gagal", "Username atau password tidak sesuai.", "error");
  }
};

// Open create account modal and populate employee list
$("#createAccountBtn")?.addEventListener("click", () => {
  const sel = $("#createEmployee");
  if (sel) {
    sel.innerHTML = '<option value="">-- Tidak ada --</option>' + (E||[]).map(e => `<option value="${e.id}">${esc(e.name)}</option>`).join("");
  }
  new bootstrap.Modal($("#createAccountModal")).show();
});

// Create account form submit: saves to AUTH_KEY as user, auto-login and redirect to user view
$("#createAccountForm").onsubmit = e => {
  e.preventDefault();
  const name = $("#createName").value.trim();
  const username = $("#createUsername").value.trim();
  const password = $("#createPassword").value;
  const employeeId = $("#createEmployee").value || "";
  if (!username || !password) { Swal.fire("Gagal", "Username dan password wajib diisi.", "error"); return; }
  const auth = authConfig();
  // ensure username uniqueness
  if ((auth.admin && auth.admin.username === username) || (auth.users||[]).some(u=>u.username===username)) {
    Swal.fire("Gagal", "Username sudah digunakan.", "error");
    return;
  }
  auth.users = [...(auth.users||[]), { name, username, password, employeeId }];
  auth.user = auth.users[auth.users.length-1];
  saveAuth(auth);
  // auto-login as user
  currentRole = "user";
  sessionStorage.setItem(SESSION_KEY, "1");
  sessionStorage.setItem("simkoja_role", "user");
  sessionStorage.setItem("simkoja_username", username);
  $("#login").classList.add("d-none");
  $("#app").classList.remove("d-none");
  updateAccountUi();
  go("dashboard");
  const modal = bootstrap.Modal.getInstance($("#createAccountModal"));
  if (modal) modal.hide();
  Swal.fire({toast:true,position:"top-end",timer:1500,showConfirmButton:false,icon:"success",title:"Akun dibuat dan masuk sebagai user"});
};
if(sessionStorage.getItem(SESSION_KEY)==="1"){$("#login").classList.add("d-none");$("#app").classList.remove("d-none");updateAccountUi();go("dashboard")}else{$("#docCount").textContent=D.length}
window.go=go;window.openEmployee=openEmployee;window.employeeDetail=employeeDetail;window.openDoc=openDoc;window.preview=preview;window.delDoc=delDoc;window.delEmp=delEmp;window.downloadDoc=downloadDoc;window.exportCSV=exportCSV;window.detailTab=detailTab;window.openRecord=openRecord;window.deleteRecord=deleteRecord;
